modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="whistle_blowers"
version="1.0.0"
displayName="Whistle Blowers"
displayURL="https://modrinth.com/project/whistle-blowers"
logoFile="logo.png"
credits="Made by GlitchyQuark using MCreator"
authors="GlitchyQuark"
description="Adds Audio Emotes (mostly whistles) for enhanced combat communication and overall fun"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.whistle_blowers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration